// Canonical ARIA-NBV glossary source.
// Humans edit this file; `make glossary` regenerates Quarto, Typst, YAML, and KG artifacts.

#import "@preview/glossarium:0.5.10": register-glossary, print-glossary, gls, glspl
#import "symbols.typ": symb
#import "equations.typ": eqs

// Rich `description` fields may use Typst content, including #symb and #eqs.
// Keep `custom` fields machine-readable so `typst query` can feed Quarto and litkg-rs.
#let aria-glossary-entries = (
  (
    key: "next-best-view",
    short: "NBV",
    long: "Next-Best-View",
    description: "Problem of selecting the next sensor viewpoint to improve an active reconstruction or inspection objective under a limited acquisition budget. In ARIA-NBV, the preferred objective is reconstruction quality improvement rather than coverage alone, with candidate views ranked by oracle or learned RRI scores.",
    group: "Planning",
    custom: (
      anchor: "term-next-best-view",
      aliases: (
        "next best view",
        "viewpoint selection",
        "view planning",
      ),
      category: "planning.view_selection",
      parent: "view-planning",
      definition_short: "Problem of selecting the next sensor viewpoint to improve an active reconstruction or inspection objective under a limited acquisition budget.",
      definition_long: "In ARIA-NBV, the preferred objective is reconstruction quality improvement rather than coverage alone, with candidate views ranked by oracle or learned RRI scores.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
        "docs/contents/thesis/roadmap.qmd",
        "docs/contents/thesis/questions.qmd#research-questions",
      ),
      citations: (
        "VIN-NBV-frahm2025",
        "GenNBV-chen2024",
      ),
      related: (
        "candidate-view",
        "relative-reconstruction-improvement",
        "view-introspection-network",
      ),
      kg_tags: (
        "planning",
        "active-reconstruction",
      ),
      typst_macro: "NBV",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "relative-reconstruction-improvement",
    short: "RRI",
    long: "Relative Reconstruction Improvement",
    description: "Metric quantifying the relative reconstruction-quality improvement obtained by adding a candidate observation to the current reconstruction. ARIA-NBV computes RRI by comparing reconstruction error before and after fusing candidate-view geometry, usually against an ASE ground-truth mesh for oracle supervision and evaluation.",
    group: "Metrics",
    custom: (
      anchor: "term-relative-reconstruction-improvement",
      aliases: (
        "reconstruction-quality gain",
        "relative quality improvement",
      ),
      category: "metrics.reconstruction_quality",
      parent: "reconstruction-quality",
      definition_short: "Metric quantifying the relative reconstruction-quality improvement obtained by adding a candidate observation to the current reconstruction.",
      definition_long: "ARIA-NBV computes RRI by comparing reconstruction error before and after fusing candidate-view geometry, usually against an ASE ground-truth mesh for oracle supervision and evaluation.",
      internal_links: (
        "docs/contents/theory/rri_theory.qmd",
        "docs/contents/impl/rri_computation.qmd",
        "docs/contents/literature/vin_nbv.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "oracle-rri",
        "target-specific-rri",
        "candidate-view",
      ),
      kg_tags: (
        "metric",
        "oracle-label",
        "reconstruction-quality",
      ),
      typst_macro: "RRI",
      notation: (
        typst: "#symb.oracle.rri",
      ),
      formula: (
        tex: "\\mathrm{RRI}(q)=\\frac{d(P_t,M)-d(P_t\\cup P_q,M)}{d(P_t,M)+\\varepsilon}",
        typst: "$\"RRI\"(q) = (d(#(symb.oracle.points)_t, M) - d(#(symb.oracle.points)_t union #(symb.oracle.points_q), M)) / (d(#(symb.oracle.points)_t, M) + epsilon)$",
      ),
      formulae: (),
    ),
  ),
  (
    key: "ground-truth",
    short: "GT",
    long: "Ground Truth",
    description: "Reference data or annotations treated as the trusted target for training, validation, or evaluation. In ARIA-NBV, ground truth usually refers to ASE meshes, object annotations, poses, or labels used to compute oracle supervision and diagnostic metrics.",
    group: "Metrics",
    custom: (
      anchor: "term-ground-truth",
      aliases: (
        "reference annotation",
        "oracle reference",
      ),
      category: "metrics.reference",
      parent: "supervision",
      definition_short: "Reference data or annotations treated as the trusted target for training, validation, or evaluation.",
      definition_long: "In ARIA-NBV, ground truth usually refers to ASE meshes, object annotations, poses, or labels used to compute oracle supervision and diagnostic metrics.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/impl/rri_computation.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "oracle-rri",
        "relative-reconstruction-improvement",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "supervision",
        "evaluation",
        "ground-truth",
      ),
      typst_macro: "GT",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-of-interest",
    short: "target",
    long: "Target of Interest",
    description: "Selected entity, object crop, point, region, or surface-deficit hypothesis whose reconstruction quality should be improved. Target-conditioned ARIA-NBV variants use this target as an explicit input to candidate scoring and planning instead of optimizing only scene-level RRI.",
    group: "Entity",
    custom: (
      anchor: "term-target-of-interest",
      aliases: (
        "target entity",
        "object of interest",
        "inspection target",
        "task target",
      ),
      category: "entity.targeting",
      parent: "entity-aware-rri",
      definition_short: "Selected entity, object crop, point, region, or surface-deficit hypothesis whose reconstruction quality should be improved.",
      definition_long: "Target-conditioned ARIA-NBV variants use this target as an explicit input to candidate scoring and planning instead of optimizing only scene-level RRI.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/contents/thesis/questions.qmd#rq4-model",
        "docs/contents/impl/vin_v2_feature_proposals.qmd",
      ),
      citations: (),
      related: (
        "target-specific-rri",
        "target-conditioned-scorer",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "entity-aware",
        "target-conditioned",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-specific-rri",
    short: "target RRI",
    long: "Target-Specific RRI",
    description: "RRI computed only on the ground-truth and reconstructed geometry associated with a selected target of interest. Target-specific RRI lets the thesis compare views by how much they improve a selected object or region, even when scene-level RRI would prefer large background surfaces.",
    group: "Metrics",
    custom: (
      anchor: "term-target-specific-rri",
      aliases: (
        "entity RRI",
        "object RRI",
        "target RRI",
      ),
      category: "metrics.reconstruction_quality",
      parent: "relative-reconstruction-improvement",
      definition_short: "RRI computed only on the ground-truth and reconstructed geometry associated with a selected target of interest.",
      definition_long: "Target-specific RRI lets the thesis compare views by how much they improve a selected object or region, even when scene-level RRI would prefer large background surfaces.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq1-objective",
        "docs/contents/thesis/questions.qmd#rq4-model",
        "docs/contents/impl/rri_computation.qmd#entity-wise-rri",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "target-of-interest",
        "acquisition-cost",
      ),
      kg_tags: (
        "metric",
        "entity-aware",
        "thesis-core",
      ),
      typst_macro: none,
      notation: (
        typst: "$RRI_e$",
      ),
      formula: (
        tex: "\\mathrm{RRI}_e(q)=\\frac{d(P_t^e,M_e)-d(P_t^e\\cup P_q^e,M_e)}{d(P_t^e,M_e)+\\varepsilon}",
      ),
      formulae: (),
    ),
  ),
  (
    key: "acquisition-cost",
    short: "cost",
    long: "Acquisition Cost",
    description: "Budget consumed to acquire observations, measured by view count, path length, elapsed time, invalid-action rate, or a weighted combination. The thesis should first report cumulative target RRI and acquisition cost separately, then use scalarized objectives only when the tradeoff is explicit.",
    group: "Planning",
    custom: (
      anchor: "term-acquisition-cost",
      aliases: (
        "capture budget",
        "view budget",
        "motion cost",
      ),
      category: "planning.objective",
      parent: "trajectory-objective",
      definition_short: "Budget consumed to acquire observations, measured by view count, path length, elapsed time, invalid-action rate, or a weighted combination.",
      definition_long: "The thesis should first report cumulative target RRI and acquisition cost separately, then use scalarized objectives only when the tradeoff is explicit.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq1-objective",
        "docs/contents/thesis/roadmap.qmd#roadmap-m5",
      ),
      citations: (),
      related: (
        "target-specific-rri",
        "candidate-view",
        "next-best-view",
      ),
      kg_tags: (
        "objective",
        "planning",
        "evaluation",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-conditioned-scorer",
    short: "target-conditioned scorer",
    long: "Target-Conditioned Scorer",
    description: "VIN-style candidate scorer that receives scene state, a candidate view, and an encoding of the target of interest. The scorer predicts target-specific utility so view ranking can prioritize a selected entity or region instead of only optimizing scene-level RRI.",
    group: "Model",
    custom: (
      anchor: "term-target-conditioned-scorer",
      aliases: (
        "target-conditioned VIN",
        "target-aware scorer",
      ),
      category: "model.scoring",
      parent: "view-introspection-network",
      definition_short: "VIN-style candidate scorer that receives scene state, a candidate view, and an encoding of the target of interest.",
      definition_long: "The scorer predicts target-specific utility so view ranking can prioritize a selected entity or region instead of only optimizing scene-level RRI.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq4-model",
        "docs/contents/impl/vin_nbv.qmd",
        "docs/reference/aria_nbv.vin.model_v3.VinModelV3.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "target-of-interest",
        "target-specific-rri",
        "view-introspection-network",
      ),
      kg_tags: (
        "model",
        "target-conditioned",
        "vin",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "aria-synthetic-environments",
    short: "ASE",
    long: "Aria Synthetic Environments",
    description: "Large-scale synthetic indoor dataset with simulated Project Aria sensor characteristics, egocentric trajectories, and scene annotations. ARIA-NBV uses ASE snippets and the public mesh-supervised subset to generate oracle RRI labels from ground-truth meshes and semi-dense point clouds.",
    group: "Dataset",
    custom: (
      anchor: "term-aria-synthetic-environments",
      aliases: (
        "Aria Synthetic Environment",
        "ASE dataset",
      ),
      category: "dataset.synthetic",
      parent: "dataset",
      definition_short: "Large-scale synthetic indoor dataset with simulated Project Aria sensor characteristics, egocentric trajectories, and scene annotations.",
      definition_long: "ARIA-NBV uses ASE snippets and the public mesh-supervised subset to generate oracle RRI labels from ground-truth meshes and semi-dense point clouds.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/setup.qmd#aria-synthetic-environments",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "snippet",
        "egocentric-foundation-model-3d",
        "oracle-rri",
      ),
      kg_tags: (
        "dataset",
        "synthetic",
        "project-aria",
      ),
      typst_macro: "ASE",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "egocentric-foundation-model-3d",
    short: "EFM3D",
    long: "Egocentric Foundation Model 3D",
    description: "Egocentric 3D foundation-model stack used as the frozen spatial backbone for ARIA-NBV candidate scoring. The current project uses EFM3D and its EVL architecture to expose voxel occupancy, centerness, semantic, and OBB evidence for VIN-style RRI prediction.",
    group: "Model",
    custom: (
      anchor: "term-egocentric-foundation-model-3d",
      aliases: (
        "EFM",
        "egocentric foundation model",
      ),
      category: "model.backbone",
      parent: "foundation-model",
      definition_short: "Egocentric 3D foundation-model stack used as the frozen spatial backbone for ARIA-NBV candidate scoring.",
      definition_long: "The current project uses EFM3D and its EVL architecture to expose voxel occupancy, centerness, semantic, and OBB evidence for VIN-style RRI prediction.",
      internal_links: (
        "docs/contents/literature/efm3d.qmd",
        "docs/contents/ext-impl/efm3d_implementation.qmd",
        "docs/contents/impl/vin_nbv.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "egocentric-voxel-lifting",
        "view-introspection-network",
        "aria-synthetic-environments",
      ),
      kg_tags: (
        "foundation-model",
        "backbone",
        "evl",
      ),
      typst_macro: "EFM3D",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "egocentric-voxel-lifting",
    short: "EVL",
    long: "Egocentric Voxel Lifting",
    description: "EFM3D architecture that lifts synchronized egocentric observations into a gravity-aligned 3D voxel feature volume. ARIA-NBV uses EVL head outputs and voxel evidence as the frozen scene representation for VIN-style RRI prediction.",
    group: "Model",
    custom: (
      anchor: "term-egocentric-voxel-lifting",
      aliases: (
        "voxel lifting",
        "EVL backbone",
      ),
      category: "model.backbone",
      parent: "egocentric-foundation-model-3d",
      definition_short: "EFM3D architecture that lifts synchronized egocentric observations into a gravity-aligned 3D voxel feature volume.",
      definition_long: "ARIA-NBV uses EVL head outputs and voxel evidence as the frozen scene representation for VIN-style RRI prediction.",
      internal_links: (
        "docs/contents/literature/efm3d.qmd",
        "docs/contents/ext-impl/efm3d_implementation.qmd",
        "docs/reference/aria_nbv.vin.backbone_evl.EvlBackbone.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
        "EVL-Doc-2025",
      ),
      related: (
        "egocentric-foundation-model-3d",
        "view-introspection-network",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "backbone",
        "voxel",
        "evl",
      ),
      typst_macro: "EVL",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "oriented-bounding-box",
    short: "OBB",
    long: "Oriented Bounding Box",
    description: "3D bounding box with arbitrary orientation, used to represent object extent more tightly than an axis-aligned box. OBBs are a natural target encoding for entity-aware ARIA-NBV because they provide center, extent, orientation, semantic class, and confidence signals.",
    group: "Geometry",
    custom: (
      anchor: "term-oriented-bounding-box",
      aliases: (
        "oriented box",
        "object box",
      ),
      category: "geometry.annotation",
      parent: "object-geometry",
      definition_short: "3D bounding box with arbitrary orientation, used to represent object extent more tightly than an axis-aligned box.",
      definition_long: "OBBs are a natural target encoding for entity-aware ARIA-NBV because they provide center, extent, orientation, semantic class, and confidence signals.",
      internal_links: (
        "docs/contents/ase_dataset.qmd#oriented-bounding-boxes",
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/contents/impl/vin_v2_feature_proposals.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "target-of-interest",
        "target-conditioned-scorer",
        "egocentric-voxel-lifting",
      ),
      kg_tags: (
        "geometry",
        "entity-aware",
        "annotation",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "frustum",
    short: "frustum",
    long: "Frustum",
    description: "Truncated pyramidal camera-visible volume bounded by near and far clipping planes plus lateral field-of-view planes. Candidate-view frusta define which scene surfaces can project into a camera image and are therefore central to visibility, rendering, and RRI diagnostics.",
    group: "Geometry",
    custom: (
      anchor: "term-frustum",
      aliases: (
        "viewing frustum",
        "camera frustum",
      ),
      category: "geometry.camera",
      parent: "camera-geometry",
      definition_short: "Truncated pyramidal camera-visible volume bounded by near and far clipping planes plus lateral field-of-view planes.",
      definition_long: "Candidate-view frusta define which scene surfaces can project into a camera image and are therefore central to visibility, rendering, and RRI diagnostics.",
      internal_links: (
        "docs/contents/impl/rri_computation.qmd",
        "docs/contents/impl/vin_nbv.qmd",
      ),
      citations: (
        "Frustum-Wikipedia-2025",
      ),
      related: (
        "candidate-view",
        "egocentric-voxel-lifting",
        "point-cloud",
      ),
      kg_tags: (
        "geometry",
        "camera",
        "visibility",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "left-up-forward",
    short: "LUF",
    long: "Left-Up-Forward",
    description: "Camera coordinate convention whose x axis points left, y axis points up, and z axis points forward. LUF is one of the coordinate-frame conventions that must stay explicit when moving between Project Aria cameras, PyTorch3D cameras, and ARIA-NBV candidate poses.",
    group: "Geometry",
    custom: (
      anchor: "term-left-up-forward",
      aliases: (
        "LUF frame",
        "left up forward",
      ),
      category: "geometry.frames",
      parent: "coordinate-frame",
      definition_short: "Camera coordinate convention whose x axis points left, y axis points up, and z axis points forward.",
      definition_long: "LUF is one of the coordinate-frame conventions that must stay explicit when moving between Project Aria cameras, PyTorch3D cameras, and ARIA-NBV candidate poses.",
      internal_links: (
        "docs/typst/seminar_paper/sections/05-coordinate-conventions.typ",
        "docs/typst/seminar_paper/sections/12f-appendix-pose-frames.typ",
      ),
      citations: (),
      related: (
        "candidate-view",
        "frustum",
      ),
      kg_tags: (
        "geometry",
        "coordinate-frame",
        "camera",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "simultaneous-localization-and-mapping",
    short: "SLAM",
    long: "Simultaneous Localization and Mapping",
    description: "Method for estimating sensor motion while building a map of the surrounding scene. In ARIA-NBV, logged SLAM poses and semi-dense points form the current reconstruction state against which candidate-view RRI is evaluated.",
    group: "Reconstruction",
    custom: (
      anchor: "term-simultaneous-localization-and-mapping",
      aliases: (
        "visual SLAM",
        "mapping and localization",
      ),
      category: "reconstruction.state",
      parent: "reconstruction",
      definition_short: "Method for estimating sensor motion while building a map of the surrounding scene.",
      definition_long: "In ARIA-NBV, logged SLAM poses and semi-dense points form the current reconstruction state against which candidate-view RRI is evaluated.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "point-cloud",
        "snippet",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "reconstruction",
        "pose",
        "project-aria",
      ),
      typst_macro: "SLAM",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "visual-inertial-odometry",
    short: "VIO",
    long: "Visual-Inertial Odometry",
    description: "Pose-estimation method that combines visual measurements from cameras with inertial measurements from IMUs. Project Aria pose and mapping products build on visual-inertial estimation, and ARIA-NBV depends on those pose streams for snippet state and candidate frame contracts.",
    group: "Reconstruction",
    custom: (
      anchor: "term-visual-inertial-odometry",
      aliases: (
        "visual inertial odometry",
        "inertial visual odometry",
      ),
      category: "reconstruction.pose",
      parent: "simultaneous-localization-and-mapping",
      definition_short: "Pose-estimation method that combines visual measurements from cameras with inertial measurements from IMUs.",
      definition_long: "Project Aria pose and mapping products build on visual-inertial estimation, and ARIA-NBV depends on those pose streams for snippet state and candidate frame contracts.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/theory/semi-dense-pc.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "simultaneous-localization-and-mapping",
        "motion-trajectory-data",
      ),
      kg_tags: (
        "pose",
        "reconstruction",
        "project-aria",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "point-cloud",
    short: "PC",
    long: "Point Cloud",
    description: "Set of 3D points representing observed scene geometry. ARIA-NBV compares current and candidate-fused point clouds against ground-truth meshes to compute oracle RRI and surface-distance diagnostics.",
    group: "Reconstruction",
    custom: (
      anchor: "term-point-cloud",
      aliases: (
        "3D points",
        "semi-dense point cloud",
      ),
      category: "reconstruction.representation",
      parent: "reconstruction",
      definition_short: "Set of 3D points representing observed scene geometry.",
      definition_long: "ARIA-NBV compares current and candidate-fused point clouds against ground-truth meshes to compute oracle RRI and surface-distance diagnostics.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
        "docs/contents/theory/surface_metrics.qmd",
        "docs/contents/impl/rri_computation.qmd",
      ),
      citations: (),
      related: (
        "relative-reconstruction-improvement",
        "oracle-rri",
        "simultaneous-localization-and-mapping",
      ),
      kg_tags: (
        "geometry",
        "reconstruction",
        "point-cloud",
      ),
      typst_macro: "PC",
      notation: (
        typst: "#symb.oracle.points",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "track",
    short: "track",
    long: "Track",
    description: "Temporal sequence of corresponding image-feature detections across frames, usually carrying per-frame image coordinates, timestamps, and camera IDs. Tracks can be triangulated or optimized into 3D points, making them a bridge between image evidence and the semi-dense point clouds used by ARIA-NBV.",
    group: "Reconstruction",
    custom: (
      anchor: "term-track",
      aliases: (
        "feature track",
        "2D track",
        "SLAM track",
      ),
      category: "reconstruction.features",
      parent: "simultaneous-localization-and-mapping",
      definition_short: "Temporal sequence of corresponding image-feature detections across frames, usually carrying per-frame image coordinates, timestamps, and camera IDs.",
      definition_long: "Tracks can be triangulated or optimized into 3D points, making them a bridge between image evidence and the semi-dense point clouds used by ARIA-NBV.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
      ),
      citations: (),
      related: (
        "point-cloud",
        "simultaneous-localization-and-mapping",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "feature-track",
        "slam",
        "reconstruction",
      ),
      typst_macro: none,
      notation: (:),
      formula: (
        tex: "\\mathcal{T}=\\{(u_k,v_k,\\mathrm{cam}_k,t_k)\\}_{k=0}^{N}",
      ),
      formulae: (),
    ),
  ),
  (
    key: "snippet",
    short: "snippet",
    long: "Snippet",
    description: "Short synchronized temporal window of Aria sensor data used as one EVL/VIN input sample. A snippet typically contains RGB or grayscale streams, poses, calibration, semi-dense points, and scene metadata that EVL lifts into a voxel grid.",
    group: "Dataset",
    custom: (
      anchor: "term-snippet",
      aliases: (
        "temporal window",
        "ASE snippet",
      ),
      category: "dataset.sample",
      parent: "aria-synthetic-environments",
      definition_short: "Short synchronized temporal window of Aria sensor data used as one EVL/VIN input sample.",
      definition_long: "A snippet typically contains RGB or grayscale streams, poses, calibration, semi-dense points, and scene metadata that EVL lifts into a voxel grid.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/impl/data_pipeline_overview.qmd",
        "docs/contents/impl/vin_nbv.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "aria-synthetic-environments",
        "egocentric-voxel-lifting",
        "view-introspection-network",
      ),
      kg_tags: (
        "dataset",
        "sample",
        "evl",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "central-pupil-frame",
    short: "CPF",
    long: "Central Pupil Frame",
    description: "Coordinate frame placed at the midpoint between the left and right eye boxes of Project Aria glasses. CPF is used by Project Aria for gaze-related quantities and should remain distinct from rig, camera, world, and PyTorch3D frames in ARIA-NBV docs.",
    group: "Dataset",
    custom: (
      anchor: "term-central-pupil-frame",
      aliases: (
        "central pupil coordinate frame",
      ),
      category: "dataset.frames",
      parent: "project-aria",
      definition_short: "Coordinate frame placed at the midpoint between the left and right eye boxes of Project Aria glasses.",
      definition_long: "CPF is used by Project Aria for gaze-related quantities and should remain distinct from rig, camera, world, and PyTorch3D frames in ARIA-NBV docs.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "left-up-forward",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "project-aria",
        "coordinate-frame",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "machine-perception-services",
    short: "MPS",
    long: "Machine Perception Services",
    description: "Project Aria processing services that derive pose, mapping, gaze, hand, and related perception outputs from sensor recordings. ARIA-NBV mainly depends on MPS-style pose and semi-dense mapping products as the current reconstruction state for RRI computation.",
    group: "Dataset",
    custom: (
      anchor: "term-machine-perception-services",
      aliases: (
        "Project Aria MPS",
      ),
      category: "dataset.project_aria",
      parent: "project-aria",
      definition_short: "Project Aria processing services that derive pose, mapping, gaze, hand, and related perception outputs from sensor recordings.",
      definition_long: "ARIA-NBV mainly depends on MPS-style pose and semi-dense mapping products as the current reconstruction state for RRI computation.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/theory/semi-dense-pc.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "simultaneous-localization-and-mapping",
        "point-cloud",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "project-aria",
        "data-product",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "motion-trajectory-data",
    short: "MTD",
    long: "Motion Trajectory Data",
    description: "Device poses over time, usually represented as a sequence of 6-DoF transformations. MTD supplies the logged egocentric trajectory used to define snippet state, current reconstruction context, and candidate-view reference poses.",
    group: "Dataset",
    custom: (
      anchor: "term-motion-trajectory-data",
      aliases: (
        "trajectory data",
        "pose stream",
      ),
      category: "dataset.stream",
      parent: "snippet",
      definition_short: "Device poses over time, usually represented as a sequence of 6-DoF transformations.",
      definition_long: "MTD supplies the logged egocentric trajectory used to define snippet state, current reconstruction context, and candidate-view reference poses.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/impl/data_pipeline_overview.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "snippet",
        "visual-inertial-odometry",
        "candidate-view",
      ),
      kg_tags: (
        "dataset",
        "pose",
        "trajectory",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "multi-frame-camera-data",
    short: "MFCD",
    long: "Multi-Frame Camera Data",
    description: "Synchronized camera streams from multiple Project Aria cameras over a temporal window. MFCD provides the egocentric image evidence consumed by EVL and aligned with pose, calibration, and semi-dense point streams.",
    group: "Dataset",
    custom: (
      anchor: "term-multi-frame-camera-data",
      aliases: (
        "multi-camera frame data",
        "synchronized camera data",
      ),
      category: "dataset.stream",
      parent: "snippet",
      definition_short: "Synchronized camera streams from multiple Project Aria cameras over a temporal window.",
      definition_long: "MFCD provides the egocentric image evidence consumed by EVL and aligned with pose, calibration, and semi-dense point streams.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/literature/efm3d.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "snippet",
        "egocentric-voxel-lifting",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "dataset",
        "camera",
        "evl",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "multi-semi-dense-point-data",
    short: "MSDPD",
    long: "Multi-Semi-Dense Point Data",
    description: "Semi-dense 3D point observations generated by SLAM-style processing across a snippet or trajectory window. MSDPD is the sparse observed geometry that ARIA-NBV fuses with candidate point clouds and compares against ground-truth meshes for RRI labels.",
    group: "Dataset",
    custom: (
      anchor: "term-multi-semi-dense-point-data",
      aliases: (
        "multi-frame semi-dense points",
        "semi-dense point stream",
      ),
      category: "dataset.stream",
      parent: "snippet",
      definition_short: "Semi-dense 3D point observations generated by SLAM-style processing across a snippet or trajectory window.",
      definition_long: "MSDPD is the sparse observed geometry that ARIA-NBV fuses with candidate point clouds and compares against ground-truth meshes for RRI labels.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
        "docs/contents/impl/rri_computation.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "point-cloud",
        "simultaneous-localization-and-mapping",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "dataset",
        "point-cloud",
        "reconstruction",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "virtual-reality-standard",
    short: "VRS",
    long: "Virtual Reality Standard",
    description: "File format used by Project Aria tooling to store multi-modal sensor recordings efficiently. VRS is part of the upstream Project Aria ecosystem, while ARIA-NBV primarily consumes ASE/ATEK-derived tensorized snippets for current experiments.",
    group: "Dataset",
    custom: (
      anchor: "term-virtual-reality-standard",
      aliases: (
        "VRS file",
        "Project Aria VRS",
      ),
      category: "dataset.file_format",
      parent: "project-aria",
      definition_short: "File format used by Project Aria tooling to store multi-modal sensor recordings efficiently.",
      definition_long: "VRS is part of the upstream Project Aria ecosystem, while ARIA-NBV primarily consumes ASE/ATEK-derived tensorized snippets for current experiments.",
      internal_links: (
        "docs/contents/setup.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "snippet",
        "multi-frame-camera-data",
        "motion-trajectory-data",
      ),
      kg_tags: (
        "project-aria",
        "file-format",
        "dataset",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "scene-script-language",
    short: "SSL",
    long: "SceneScript Language",
    description: "Structured language representation for indoor scene layout using primitives such as walls, doors, windows, and objects. SceneScript is relevant to ARIA-NBV as a possible semantic/global planning layer and as one source of ASE scene-structure context.",
    group: "Dataset",
    custom: (
      anchor: "term-scene-script-language",
      aliases: (
        "Structure Scene Language",
        "SceneScript structured language",
      ),
      category: "dataset.scene_representation",
      parent: "scene-representation",
      definition_short: "Structured language representation for indoor scene layout using primitives such as walls, doors, windows, and objects.",
      definition_long: "SceneScript is relevant to ARIA-NBV as a possible semantic/global planning layer and as one source of ASE scene-structure context.",
      internal_links: (
        "docs/contents/literature/scene_script.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "SceneScript-avetisyan2024",
      ),
      related: (
        "aria-synthetic-environments",
        "target-of-interest",
        "next-best-view",
      ),
      kg_tags: (
        "scene-representation",
        "semantics",
        "extension",
      ),
      typst_macro: "SSL",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "candidate-view",
    short: "candidate",
    long: "Candidate View",
    description: "Proposed camera pose whose expected reconstruction utility is evaluated before selecting the next observation. ARIA-NBV samples candidate views around a reference pose or target, renders candidate depths from the mesh for oracle labels, and scores candidates with RRI or learned VIN predictions.",
    group: "Planning",
    custom: (
      anchor: "term-candidate-view",
      aliases: (
        "candidate pose",
        "candidate viewpoint",
        "next-view candidate",
      ),
      category: "planning.action",
      parent: "next-best-view",
      definition_short: "Proposed camera pose whose expected reconstruction utility is evaluated before selecting the next observation.",
      definition_long: "ARIA-NBV samples candidate views around a reference pose or target, renders candidate depths from the mesh for oracle labels, and scores candidates with RRI or learned VIN predictions.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq3-candidates",
        "docs/contents/impl/rri_computation.qmd",
        "docs/reference/aria_nbv.pose_generation.CandidateViewGenerator.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "next-best-view",
        "oracle-rri",
        "target-conditioned-scorer",
      ),
      kg_tags: (
        "planning",
        "action-space",
        "candidate-generation",
      ),
      typst_macro: none,
      notation: (
        typst: "#symb.oracle.candidates",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "oracle-rri",
    short: "oracle RRI",
    long: "Oracle RRI",
    description: "RRI label computed with privileged ground-truth geometry, used for supervised training and evaluation. The current oracle renders candidate depth maps from ASE ground-truth meshes, backprojects candidate point clouds, fuses them with the current semi-dense reconstruction, and scores the resulting surface-distance improvement.",
    group: "Supervision",
    custom: (
      anchor: "term-oracle-rri",
      aliases: (
        "RRI oracle",
        "oracle label",
        "mesh-supervised RRI",
      ),
      category: "supervision.oracle",
      parent: "relative-reconstruction-improvement",
      definition_short: "RRI label computed with privileged ground-truth geometry, used for supervised training and evaluation.",
      definition_long: "The current oracle renders candidate depth maps from ASE ground-truth meshes, backprojects candidate point clouds, fuses them with the current semi-dense reconstruction, and scores the resulting surface-distance improvement.",
      internal_links: (
        "docs/contents/impl/rri_computation.qmd",
        "docs/contents/impl/data_pipeline_overview.qmd",
        "docs/contents/thesis/roadmap.qmd#roadmap-m1",
      ),
      citations: (
        "VIN-NBV-frahm2025",
        "EFM3D-straub2024",
      ),
      related: (
        "relative-reconstruction-improvement",
        "candidate-view",
        "aria-synthetic-environments",
      ),
      kg_tags: (
        "oracle",
        "supervision",
        "mesh",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "view-introspection-network",
    short: "VIN",
    long: "View Introspection Network",
    description: "Learned candidate-view scorer that predicts RRI or an ordinal RRI-derived utility without capturing the candidate view. ARIA-NBV adapts VIN-NBV by placing a lightweight RRI prediction head on top of frozen EVL features and candidate-pose evidence from ASE snippets.",
    group: "Model",
    custom: (
      anchor: "term-view-introspection-network",
      aliases: (
        "VIN scorer",
        "VIN-NBV model",
        "Aria-VIN-NBV",
      ),
      category: "model.scoring",
      parent: "next-best-view",
      definition_short: "Learned candidate-view scorer that predicts RRI or an ordinal RRI-derived utility without capturing the candidate view.",
      definition_long: "ARIA-NBV adapts VIN-NBV by placing a lightweight RRI prediction head on top of frozen EVL features and candidate-pose evidence from ASE snippets.",
      internal_links: (
        "docs/contents/literature/vin_nbv.qmd",
        "docs/contents/impl/vin_nbv.qmd",
        "docs/reference/aria_nbv.vin.model_v3.VinModelV3.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "target-conditioned-scorer",
        "egocentric-voxel-lifting",
      ),
      kg_tags: (
        "model",
        "vin",
        "candidate-scoring",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "coverage-ratio",
    short: "CR",
    long: "Coverage Ratio",
    description: "Fraction of a target surface, scene, or region treated as observed under a chosen visibility or distance threshold. Coverage ratio is a useful diagnostic baseline for NBV, but ARIA-NBV treats reconstruction-quality improvement through RRI as the preferred optimization target.",
    group: "Metrics",
    custom: (
      anchor: "term-coverage-ratio",
      aliases: (
        "coverage ratio",
      ),
      category: "metrics.coverage",
      parent: "evaluation-metric",
      definition_short: "Fraction of a target surface, scene, or region treated as observed under a chosen visibility or distance threshold.",
      definition_long: "Coverage ratio is a useful diagnostic baseline for NBV, but ARIA-NBV treats reconstruction-quality improvement through RRI as the preferred optimization target.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
        "docs/contents/impl/rri_computation.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "candidate-view",
      ),
      kg_tags: (
        "metric",
        "coverage",
      ),
      typst_macro: "CR",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "chamfer-distance",
    short: "CD",
    long: "Chamfer Distance",
    description: "Bidirectional point-set distance commonly used to compare reconstructed points against reference geometry. ARIA-NBV uses point-to-mesh and Chamfer-style distances as reconstruction error components when deriving oracle RRI labels and diagnostics.",
    group: "Metrics",
    custom: (
      anchor: "term-chamfer-distance",
      aliases: (
        "Chamfer metric",
      ),
      category: "metrics.reconstruction_quality",
      parent: "reconstruction-quality",
      definition_short: "Bidirectional point-set distance commonly used to compare reconstructed points against reference geometry.",
      definition_long: "ARIA-NBV uses point-to-mesh and Chamfer-style distances as reconstruction error components when deriving oracle RRI labels and diagnostics.",
      internal_links: (
        "docs/contents/impl/rri_computation.qmd",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "point-cloud",
        "ground-truth",
      ),
      kg_tags: (
        "metric",
        "reconstruction-quality",
      ),
      typst_macro: "CD",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "degrees-of-freedom",
    short: "DoF",
    long: "Degrees of Freedom",
    description: "Number of independent pose parameters available to a camera, object, or action representation. ARIA-NBV distinguishes full 6-DoF pose estimation from reduced 5-DoF candidate or action spaces used for practical view planning.",
    group: "Geometry",
    custom: (
      anchor: "term-degrees-of-freedom",
      aliases: (
        "DoF",
      ),
      category: "geometry.pose",
      parent: "pose",
      definition_short: "Number of independent pose parameters available to a camera, object, or action representation.",
      definition_long: "ARIA-NBV distinguishes full 6-DoF pose estimation from reduced 5-DoF candidate or action spaces used for practical view planning.",
      internal_links: (
        "docs/typst/seminar_paper/sections/05-coordinate-conventions.typ",
        "docs/typst/seminar_paper/sections/12f-appendix-pose-frames.typ",
      ),
      citations: (),
      related: (
        "candidate-view",
      ),
      kg_tags: (
        "geometry",
        "pose",
      ),
      typst_macro: "DoF",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "six-degrees-of-freedom",
    short: "6DoF",
    long: "Six Degrees of Freedom",
    description: "Pose parameterization with three translational and three rotational degrees of freedom. Project Aria poses, candidate cameras, and world-to-device transforms are usually represented as 6-DoF rigid-body transforms.",
    group: "Geometry",
    custom: (
      anchor: "term-six-degrees-of-freedom",
      aliases: (
        "6-DoF",
        "6 degrees of freedom",
      ),
      category: "geometry.pose",
      parent: "degrees-of-freedom",
      definition_short: "Pose parameterization with three translational and three rotational degrees of freedom.",
      definition_long: "Project Aria poses, candidate cameras, and world-to-device transforms are usually represented as 6-DoF rigid-body transforms.",
      internal_links: (
        "docs/typst/seminar_paper/sections/05-coordinate-conventions.typ",
        "docs/typst/seminar_paper/sections/12f-appendix-pose-frames.typ",
      ),
      citations: (),
      related: (
        "candidate-view",
        "degrees-of-freedom",
      ),
      kg_tags: (
        "geometry",
        "pose",
      ),
      typst_macro: "SixDoF",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "five-degrees-of-freedom",
    short: "5DoF",
    long: "Five Degrees of Freedom",
    description: "Reduced camera-action parameterization commonly used when roll is fixed or otherwise constrained. ARIA-NBV uses 5-DoF language for candidate and planning abstractions where position and viewing direction matter while roll is not an independently optimized control dimension.",
    group: "Planning",
    custom: (
      anchor: "term-five-degrees-of-freedom",
      aliases: (
        "5-DoF",
        "5 degrees of freedom",
      ),
      category: "planning.action_space",
      parent: "degrees-of-freedom",
      definition_short: "Reduced camera-action parameterization commonly used when roll is fixed or otherwise constrained.",
      definition_long: "ARIA-NBV uses 5-DoF language for candidate and planning abstractions where position and viewing direction matter while roll is not an independently optimized control dimension.",
      internal_links: (
        "docs/contents/thesis/roadmap.qmd",
        "docs/typst/seminar_paper/sections/10a-extensions.typ",
      ),
      citations: (
        "GenNBV-chen2024",
      ),
      related: (
        "candidate-view",
        "next-best-view",
        "degrees-of-freedom",
      ),
      kg_tags: (
        "planning",
        "action-space",
      ),
      typst_macro: "FiveDoF",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "area-under-curve",
    short: "AUC",
    long: "Area Under Curve",
    description: "Aggregate score computed by integrating a metric curve over an acquisition, threshold, or ranking axis. AUC can summarize how quickly reconstruction quality, coverage, or ranking quality improves as views are acquired or candidate thresholds change.",
    group: "Metrics",
    custom: (
      anchor: "term-area-under-curve",
      aliases: (
        "AUC",
      ),
      category: "metrics.evaluation",
      parent: "evaluation-metric",
      definition_short: "Aggregate score computed by integrating a metric curve over an acquisition, threshold, or ranking axis.",
      definition_long: "AUC can summarize how quickly reconstruction quality, coverage, or ranking quality improves as views are acquired or candidate thresholds change.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
      ),
      citations: (),
      related: (
        "acquisition-cost",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "metric",
        "evaluation",
      ),
      typst_macro: "AUC",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "multi-view-stereo",
    short: "MVS",
    long: "Multi-view Stereo",
    description: "Reconstruction family that estimates dense or semi-dense scene geometry from multiple calibrated views. MVS is part of the broader reconstruction context for NBV, although ARIA-NBV's current oracle labels are built from ASE meshes and Aria-style semi-dense point observations.",
    group: "Reconstruction",
    custom: (
      anchor: "term-multi-view-stereo",
      aliases: (
        "multi-view reconstruction",
      ),
      category: "reconstruction.geometry",
      parent: "reconstruction",
      definition_short: "Reconstruction family that estimates dense or semi-dense scene geometry from multiple calibrated views.",
      definition_long: "MVS is part of the broader reconstruction context for NBV, although ARIA-NBV's current oracle labels are built from ASE meshes and Aria-style semi-dense point observations.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
      ),
      citations: (),
      related: (
        "point-cloud",
        "next-best-view",
      ),
      kg_tags: (
        "reconstruction",
        "geometry",
      ),
      typst_macro: "MVS",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "occupancy-grid",
    short: "Occupancy Grid",
    long: "Occupancy Grid",
    description: "Spatial grid whose cells encode whether space is occupied, free, unknown, or represented by a related occupancy probability. Occupancy-style voxel evidence appears in EVL outputs and VIN feature construction, where it helps summarize local 3D scene state for candidate scoring.",
    group: "Representation",
    custom: (
      anchor: "term-occupancy-grid",
      aliases: (
        "occupancy volume",
      ),
      category: "representation.spatial",
      parent: "scene-representation",
      definition_short: "Spatial grid whose cells encode whether space is occupied, free, unknown, or represented by a related occupancy probability.",
      definition_long: "Occupancy-style voxel evidence appears in EVL outputs and VIN feature construction, where it helps summarize local 3D scene state for candidate scoring.",
      internal_links: (
        "docs/contents/impl/vin_nbv.qmd",
        "docs/typst/seminar_paper/sections/06-architecture.typ",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "egocentric-voxel-lifting",
        "view-introspection-network",
      ),
      kg_tags: (
        "representation",
        "voxel",
      ),
      typst_macro: "OccGrid",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "aria-digital-twin",
    short: "ADT",
    long: "Aria Digital Twin",
    description: "Project Aria dataset with real-world captures and digital-twin scene annotations. ADT is adjacent to ARIA-NBV's sim-to-real context; the current experiments focus on ASE and EFM3D/ATEK exports, while ADT remains a relevant transfer surface.",
    group: "Dataset",
    custom: (
      anchor: "term-aria-digital-twin",
      aliases: (
        "ADT",
      ),
      category: "dataset.aria",
      parent: "project-aria",
      definition_short: "Project Aria dataset with real-world captures and digital-twin scene annotations.",
      definition_long: "ADT is adjacent to ARIA-NBV's sim-to-real context; the current experiments focus on ASE and EFM3D/ATEK exports, while ADT remains a relevant transfer surface.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "aria-synthetic-environments",
        "aria-everyday-objects",
      ),
      kg_tags: (
        "dataset",
        "project-aria",
      ),
      typst_macro: "ADT",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "aria-everyday-objects",
    short: "AEO",
    long: "Aria Everyday Objects",
    description: "Small-scale real-world Project Aria object dataset used by EFM3D for egocentric 3D perception evaluation. AEO is relevant as a possible sim-to-real check for ARIA-NBV ideas that are first developed on ASE mesh-supervised snippets.",
    group: "Dataset",
    custom: (
      anchor: "term-aria-everyday-objects",
      aliases: (
        "AEO",
      ),
      category: "dataset.aria",
      parent: "project-aria",
      definition_short: "Small-scale real-world Project Aria object dataset used by EFM3D for egocentric 3D perception evaluation.",
      definition_long: "AEO is relevant as a possible sim-to-real check for ARIA-NBV ideas that are first developed on ASE mesh-supervised snippets.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "aria-synthetic-environments",
        "aria-digital-twin",
      ),
      kg_tags: (
        "dataset",
        "project-aria",
      ),
      typst_macro: "AEO",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
)

#let aria-glossary-metadata(entry) = (
  id: entry.key,
  anchor: entry.custom.anchor,
  label: entry.long,
  short: entry.short,
  aliases: entry.custom.aliases,
  category: entry.custom.category,
  parent: entry.custom.parent,
  definition_short: entry.custom.definition_short,
  definition_long: entry.custom.definition_long,
  internal_links: entry.custom.internal_links,
  citations: entry.custom.citations,
  related: entry.custom.related,
  kg_tags: entry.custom.kg_tags,
  typst_macro: entry.custom.typst_macro,
  notation: entry.custom.notation,
  formula: entry.custom.formula,
  formulae: entry.custom.formulae,
)

#let register-aria-glossary() = register-glossary(aria-glossary-entries)
#let print-aria-glossary(..args) = print-glossary(aria-glossary-entries, ..args)

#for entry in aria-glossary-entries [
  #metadata(aria-glossary-metadata(entry)) <aria-glossary-term>
]
