#let rl = (
    // RL state / observation / reward / return.
    s: $s$,
    o: $o$,
    a: $a$,
    r: $r$,
    G: $G$,
    Q: $Q$,
    V: $V$,
    pi: $pi$,
    A: $A$,
    H: $H$,
    gamma: $gamma$,
    mdp_nbv: $cal(M)_"NBV"$,
    action_set: $cal(A)(s_t)$,
    transition: $T$,
    s_hist: $s_t^"hist"$,
    s_off: $s_t^"off"$,
    s_cf0: $s_t^"cf0"$,
    s_cf_geom: $s_t^"cf+"$,
    s_oracle: $s_t^"oracle"$,
    reward_target: $r_t^e$,
    return_h: $G_t^(H)$,
    qh: $Q_H$,
    validity_mask: $m_(t,i)$,
    invalid_reason: $rho_(t,i)$,
    delta: $delta$,
    rho: $rho$,
    z: $z$,
    // Pose / persistent memory / optional entity memory / budget.
    x: $bold(x)$,
    m: $bold(m)$,
    e: $bold(e)$,
    b: $b$,
    target: $e_t$,
    budget: $b_t$,
  )
