[pytest]
testpaths = oracle_rri/tests
norecursedirs = external oracle_rri_old oracle_rri_pkg .git .venv .pytest_cache .data
addopts = -v --tb=short --strict-markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
