---
title:
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
namespace types{
    class SamplingStrategy{
        <<enumeration>>
        UNIFORM_SPHERE
        FORWARD_POWERSPHERICAL

    }
    class CollisionBackend{
        <<enumeration>>
        PYEMBREE
        TRIMESH

    }
    class CandidateContext{
    }
    class CandidateSamplingResult{
    }
}
namespace candidate_generation{
    class CandidateViewGeneratorConfig{
        -_resolve_device(cls, str v)
        +set_debug(self)
    }
    class CandidateViewGenerator{
        +config
        +console
        +\_\_init\_\_(self, CandidateViewGeneratorConfig config)
        -_build_default_rules(self)
        +generate_from_typed_sample(self, EfmSnippetView sample)
        -_occupancy_extent_from_sample(self, EfmSnippetView sample)
        +generate(self, PoseTW last_pose, gt_mesh, occupancy_extent)
        -_seed(self, CandidateContext ctx, int n)
    }
}
namespace candidate_generation_rules{
    class Rule{
        +\_\_call\_\_(self, CandidateContext ctx)
    }
    class ShellSamplingRule{
        +config
        +\_\_init\_\_(self, CandidateViewGeneratorConfig config)
        +\_\_call\_\_(self, CandidateContext ctx)
        -_sample_directions(self, int n, torch.Tensor az, torch.device device)
    }
    class MinDistanceToMeshRule{
        +config
        +\_\_init\_\_(self, CandidateViewGeneratorConfig config)
        +\_\_call\_\_(self, CandidateContext ctx)
    }
    class PathCollisionRule{
        +config
        +\_\_init\_\_(self, CandidateViewGeneratorConfig config)
        +\_\_call\_\_(self, CandidateContext ctx)
    }
    class FreeSpaceRule{
        +config
        +\_\_init\_\_(self, CandidateViewGeneratorConfig config)
        +\_\_call\_\_(self, CandidateContext ctx)
    }
}
%% inheritance
