---
title: "Action Items & TODOs"
format: html
---
<!-- Agent Instructions: Always work in a test-driven manner.  -->

# Issues & Questions

## ASE: Single Trajectory Per Scene

- Each ASE scene provides only one pre-recorded egocentric trajectory. We cannot query arbitrary novel viewpoints.
    - EFM3D introduces GT meshes for 100 validation scenes. We can use these to compute oracle RRI for candidate views. Use the mesh predicted by EFM3D as pseudo-GT for other scenes.

- depth maps in ASE dataset are ground-truth!

- non-gt point clouds are sparse! How to sample a PC from the candidate view that can be compared to the pre-existing semi-dense SLAM PC that is provided in the ASE dataset?
- Should NBV prediction output discrete selection (VIN-NBV) or continuous pose (GenNBV)?
  - Start with randomly sampled candidate views for which the RRI is computed. Action space is then the selection among these candidates.
  - Future work: learn to generate continuous poses directly, whose fitness can than be quantified using the RRI predictor; here we can also consider the free space voxels that are used in EFM3D to avoid collisions.


# Action Items


## HIGHEST PRIO:

- implement the `OracleRRI` class with PC to mesh distance computation between two point clouds
  - Mesh to distance field computation??
  - How can we consider only relevant (observable parts) of the scene, such that we don't have to consider the entire mesh (e.g. there might be different rooms that cannot be considered)
  - must be implemented as `TorchMetric`
- implement `CandidateViewGenerator`, that generated N candidate SE(3) poses (roll = 0) around the latest camera position in the trajectory. Must generate poses of type `PoseTW` (`external/efm3d/efm3d/aria/pose.py`)
- implement a `CandidateSample` that takes the candidate poses of type `PoseTW` and samples rays from the corresponding view onto the GT mesh to obtain a dense point cloud from this candidate view.
  - candidate pose generation: only within free space and within confines of the room (based on SSL for training); based on predicted occupancy from EFM3D for eval
  - ray mesh intersection: check if both poses can see each other
  - sampling based on occupancy grid?

- implement a class (name to be decided) that fuses the semi-dense SLAM PC $\mathcal{P}_t$ with the dense PC from the candidate view  $\mathcal{P}_{\mathbf{q}}$ to obtain the updated PC $\mathcal{P}_{t \cup \mathbf{q}}$.
- crop GT mesh to relevant volume around the trajectory to speed up computation, this is especially relevant for completeness computation.


### Data Handling

- Implement custom data handling for the ASE dataset, using the tools provided in ATEK:
  - Should provide easy access to the ASE dataset in ATEK WDS format together with the ground truth meshes.
  - Should wrap around their existing dataset and dataset downloader implementations to provide easy acces to the data we need.
  - Download all 3 forms of the dataset for scenes for which the GT meshes are available.
  - Figure out, how to best manage to download corresponding data files (ATEK, raw ASE, GT meshes) for the same scenes.
  - We also want to represents scenes together with the snippets that reside in them (snippets are in atek dataset structure ready for training).
  - metadata should be comined in a single file for easy access.
  - should provide mapping from scene_id to snippet_ids and vice versa.
  - should leverage their download scripts internally to provide a cleaner interface.
  - we want to be able to download meta data about all datasets withot downloading the full data to be able to explicitly see which scenes are relevant to us (i.e. in terms of having many atek snipptes and gt meshes available)
  - Selection of ATEK WDS snippets based on the available GT meshes - i.e. in `.data/aria_download_urls/ase_mesh_download_urls.json`:
    ```json
    [
    {
        "filename": "scene_ply_81022.zip",
        "cdn": "https://scontent.xx.fbcdn.net/m1/v/t6/An-P6UxdW2UCcDGjnRfIWHlkPjn7dRbmCcaQdmJGuOg5AWqcqm2x5w9i4ERYfd1_J1oxJ9OoDz-VNFw1RKmqxAA2zVlsGpGZazodN0Cu4UrRUYrXjbShQLo3s7ojK_iUQRTR5Q.zip?_nc_gid&ccb=10-5&oh=00_Afd13a-0sLEMI02bJLU1UKhIAUPjgrDupi5py69tn6xb2w&oe=691C7C49&_nc_sid=1a752d",
        "sha": "ecfcbfd76ed6079810d4305ddb718a84739b25bb"
    },
    {
        "filename": "scene_ply_81048.zip",
    ...
    }
    ]
    ```
    - The scene IDs can be extracted from the filenames (e.g. `81022` from `scene_ply_81022.zip`).
    - `.data/aria_download_urls/AriaSyntheticEnvironment_ATEK_download_urls.json` contains the download links for the ATEK WDS dataset:
      ```json
      {
    "raw_dataset_name": "AriaSyntheticEnvironment",
    "raw_dataset_release_version": "1.0",
    "atek_data_for_all_configs": {
        "cubercnn": {
            "atek_preprocessing_config_name": "cubercnn",
            "atek_wds_version": "v0.1.1",
            "atek_preprocessing_config_content": {
                "atek_config_name": "cubercnn",
                "camera_temporal_subsampler": {
                    "main_camera_label": "camera-rgb",
                    "time_domain": "DEVICE_TIME",
                    "main_camera_target_freq_hz": 10,
                    "sample_length_in_num_frames": 1,
                    "stride_length_in_num_frames": 2
                },
                "processors": {
                    "rgb": {
                        "selected": true,
                        "sensor_label": "camera-rgb",
                        "time_domain": "DEVICE_TIME",
                        "tolerance_ns": 10000000,
                        "undistort_to_linear_camera": true,
                        "target_camera_resolution": {},
                        "rotate_image_cw90deg": true
                    },
                    "slam_left": {
                        "selected": false
                    },
                    "slam_right": {
                        "selected": false
                    },
                    "mps_traj": {
                        "selected": true,
                        "tolerance_ns": 10000000
                    },
                    "mps_semidense": {
                        "selected": false
                    },
                    "obb_gt": {
                        "selected": true,
                        "tolerance_ns": 10000000,
                        "category_mapping_field_name": "category",
                        "bbox2d_num_samples_on_edge": 10
                    }
                },
                "wds_writer": {
                    "prefix_string": "AsePublicRelease2023",
                    "max_samples_per_shard": 32
                }
            },
            "atek_wds_shapes": {
                "mfcd#camera-rgb+capture_timestamps_ns": "1",
                "mfcd#camera-rgb+exposure_durations_s": "1",
                "mfcd#camera-rgb+frame_ids": "1",
                "mfcd#camera-rgb+gains": "1",
                "mfcd#camera-rgb+projection_params": "4",
                "mfcd#camera-rgb+t_device_camera": "3, 4",
                "mtd#capture_timestamps_ns": "1",
                "mtd#gravity_in_world": "3",
                "mtd#ts_world_device": "1, 3, 4",
                "mfcd#camera-rgb+images": "1, 3, 704, 704"
            },
            "atek_wds_dtypes": {
                "gt_data": "dict",
                "mfcd#camera-rgb+camera_label": "str",
                "mfcd#camera-rgb+camera_model_name": "str",
                "mfcd#camera-rgb+capture_timestamps_ns": "torch.int64",
                "mfcd#camera-rgb+exposure_durations_s": "torch.float32",
                "mfcd#camera-rgb+frame_ids": "torch.int64",
                "mfcd#camera-rgb+gains": "torch.float32",
                "mfcd#camera-rgb+origin_camera_label": "str",
                "mfcd#camera-rgb+projection_params": "torch.float32",
                "mfcd#camera-rgb+t_device_camera": "torch.float32",
                "mtd#capture_timestamps_ns": "torch.int64",
                "mtd#gravity_in_world": "torch.float32",
                "mtd#ts_world_device": "torch.float32",
                "sequence_name": "str",
                "mfcd#camera-rgb+images": "torch.uint8"
            },
            "wds_file_urls": {
                "0": {
                ...
                "81048": {
                              "shards-0000_tar": {
                                  "filename": "AriaSyntheticEnvironment_1_0_ATEK_cubercnn_81048_shards-0000.tar",
                                  "sha1sum": "05840565afd9702f985e1c483170f5d6e8825f07",
                                  "file_size_bytes": 8570880,
                                  "download_url": "https://scontent.xx.fbcdn.net/m1/v/t6/An9oQjW7U2aCTPOcBSIZbdpnELJZXW4VbKjxqjSM09txkZdhmaV-CwVmCPD3-x05L4DuXSadV_zDu_b_cGkZG52fAXuqt5_YQLP_GuikCPPYlDUqXPqJ0UDZPxGLwIJ6SERi_a3pX6K7eWUWgS1DHc1LgQ.tar/AriaSyntheticEnvironment_1_0_ATEK_cubercnn_81048_shards-0000.tar?_nc_gid&ccb=10-5&oh=00_AfeTftnWBgk7x5YeD9j7MEdoArTu2ZMPJj6ApcZJ7_SXYg&oe=691D4B7D&_nc_sid=c228f2"
                              },
                              ...
                            }
            }
        },
        ...
      }
  }
```

  ```bash
  external/ATEK/tools
  ├── ase_mesh_downloader.py
  ├── atek_wds_data_downloader.py
  ├── benchmarking_static_object_detection.py
  ├── benchmarking_surface_reconstruction.py
  ├── infer_cubercnn.py
  └── train_cubercnn.py
  ```

  ```bash
  .data/aria_download_urls
  ├── AriaSyntheticEnvironment_ATEK_download_urls.json
  ├── aria_synthetic_environments_dataset_download_urls.json
  └── ase_mesh_download_urls.json  # contains download links for 100 GT meshes ("scene_ply_<scene_id>.ply")
  ```
  - Use `external/projectaria_tools/projects/AriaSyntheticEnvironment/aria_synthetic_environments_downloader.py` to download the base ASE dataset
  ```bash
  # example: download specific scenes
  python3 projects/AriaSyntheticEnvironment/aria_synthetic_environments_downloader.py --set train --scene-ids 560-569 --cdn-file aria_synthetic_environments_dataset_download_urls.json --output-dir $HOME/projectaria_tools_ase_data --unzip True
  ```

## Lower Prio:

### Candidate Sampling Strategies
- Train a light weight network to predict the sampled rays given a canidate view and projection onto the mesh to imitate how their SAM would see it.
- Or simply generate dense PC ($\mathcal{P}_{\mathbf{t}}$) from ground truth depth maps - what high-level implementations would be suited?
-