#import "../../../shared/macros.typ": *
#import "_style.typ": *

= Motivation

Active 3D reconstruction is limited not only by the quality of the reconstruction algorithm, but also by the choice of viewpoints that provide its input. A mobile or wearable camera cannot observe all surfaces at once, and each additional acquisition consumes time, motion budget, and operator attention. The next-best-view (#NBV) problem therefore asks which view should be selected next so that a reconstruction improves as much as possible under a constrained acquisition budget. This question is especially important for egocentric indoor capture, where observations are partial, clutter is common, and many useful surfaces are visible only from a narrow range of viewpoints. The active-perception literature makes the same point at a broader level: perception improves when the agent can choose actions that change what is observable @ActivePerception-bajcsy1988 @ActiveVision-aloimonos1988.

Many NBV systems use coverage or information gain as a proxy objective. These objectives are attractive because they can often be computed from occupancy, uncertainty, or visibility fields, but they do not necessarily measure whether the final reconstructed surface becomes more accurate. VIN-NBV introduced a more direct quality-driven objective by learning to rank candidate views according to Relative Reconstruction Improvement (#RRI), an oracle signal derived from the reduction in Chamfer-style reconstruction error after adding a candidate observation @VIN-NBV-frahm2025. This idea is a strong foundation for the thesis because it separates the desired scientific target, reconstruction-quality improvement, from convenient but weaker proxies such as the number of newly covered voxels.

ARIA-NBV extends this quality-driven view-ranking idea to egocentric indoor data from the Project Aria ecosystem. Aria Synthetic Environments (#ASE) provides synthetic egocentric trajectories, calibrated camera streams, semi-dense SLAM points, object annotations, and ground-truth meshes for a supervised subset @ProjectAria-ASE-2025. EFM3D and EVL provide a compatible egocentric foundation-model representation that lifts multi-stream observations into a local 3D voxel field @EFM3D-straub2024. This makes it possible to compute expensive oracle #RRI labels in simulation, train a lightweight candidate scorer on frozen egocentric features, and keep the data representation close to real Aria recordings.

The thesis is motivated by the gap between one-step candidate ranking and useful multi-step view planning. The current implementation already supports discrete candidate generation, oracle label computation, immutable offline stores, VIN-style scoring, and early counterfactual rollout scaffolding. However, the learned scorer is still preliminary and should not be presented as a finished #NBV policy. The next credible step is to make the data and geometry trustworthy, then test whether bounded non-myopic search over trusted candidate views improves cumulative reconstruction quality over one-step greedy selection.

#thesis-box([Thesis position])[
  The core claim is deliberately narrow: ARIA-NBV should first prove that trusted, mesh-supervised candidate utility supports better one-step and bounded multi-step selection in egocentric snippets. Continuous control, learned value functions, and simulator-backed policies become credible only after that diagnostic foundation is reproducible.
]

The long-term research direction includes target-aware and task-aware view planning. Indoor reconstruction is rarely uniform in importance: a user may care more about an object, doorway, appliance, or region of missing surface than about a large already-visible wall. The thesis therefore proposes target-conditioned, quality-driven #NBV as its central direction. It keeps full continuous reinforcement learning, simulator-backed online control, and real-device deployment as later extensions, while focusing the thesis core on target-specific #RRI, discrete candidate scoring, and bounded rollout evaluation.
