#import "../../../shared/macros.typ": *
#import "_style.typ": *

= Problem and Research Contract

ARIA-NBV studies target-conditioned #NBV for egocentric indoor reconstruction. At each decision step, an agent has a partial ASE trajectory, accumulated semi-dense or rendered geometry, frozen logged EFM/EVL context, a selected target, and a finite set of candidate camera poses. The privileged ground-truth mesh and GT target crop are oracle and evaluation assets only. The main actor-visible protocol is OBS-SEL / PRED-Q / GT-EVAL: select a target from observed or predicted evidence, condition scoring and planning on the predicted/observed target record, and evaluate with matched GT target #RRI.

The thesis question is whether this setup can support target-conditioned, RRI-based multi-step view selection rather than only one-step scoring. The minimal quantitative success bar is therefore not a continuous policy. It is a discrete finite-candidate $Q_H$ model that predicts bounded cumulative target #RRI and whose selected actions are re-evaluated by the oracle. If learned $Q_H$ does not beat one-step greedy or one-step model scoring under the same acquisition budget, the thesis must report the blocker rather than reclassifying $Q_H$ as optional. The boundary is fixed: ASE snippets, GT meshes for oracle labels, EVL/EFM context, discrete candidates, and Rerun inspection are in scope; GT OBBs/crops are V0 sanity or GT-EVAL labels, not main actor input; Gumbel-Top-k, IQL, actor-critic, online simulators, and real-device runs are bridge work.

The literature role is correspondingly narrow. VIN-NBV provides the quality-driven #RRI candidate-ranking precedent @VIN-NBV-frahm2025. ASE and EFM3D provide the egocentric synthetic data and frozen representation substrate @ProjectAria-ASE-2025 @EFM3D-straub2024. GenNBV and Hestia show why continuous and hierarchical #NBV are important, but they rely on simulator/control assumptions that ARIA-NBV should not claim before the finite-candidate result exists @GenNBV-chen2024 @Hestia-lu2026. Offline RL references such as Double DQN, CQL, BCQ, Decision Transformer, and IQL guide value-learning and sequence-modeling baselines, but the first thesis path is a masked finite-candidate $Q_H$ trained from ASE oracle traces @DoubleDQN-vanHasselt2015 @CQL-kumar2020 @BCQ-fujimoto2019 @DecisionTransformer-chen2021 @IQL-kostrikov2021.
