-- Generated by scripts/glossary_build.py; edit docs/typst/shared/glossary.typ.

return {
  ["acquisition-cost"] = {
    label = "Acquisition Cost",
    short = "cost",
    anchor = "term-acquisition-cost",
  },
  ["area-under-curve"] = {
    label = "Area Under Curve",
    short = "AUC",
    anchor = "term-area-under-curve",
  },
  ["aria-digital-twin"] = {
    label = "Aria Digital Twin",
    short = "ADT",
    anchor = "term-aria-digital-twin",
  },
  ["aria-everyday-objects"] = {
    label = "Aria Everyday Objects",
    short = "AEO",
    anchor = "term-aria-everyday-objects",
  },
  ["aria-synthetic-environments"] = {
    label = "Aria Synthetic Environments",
    short = "ASE",
    anchor = "term-aria-synthetic-environments",
  },
  ["candidate-view"] = {
    label = "Candidate View",
    short = "candidate",
    anchor = "term-candidate-view",
  },
  ["central-pupil-frame"] = {
    label = "Central Pupil Frame",
    short = "CPF",
    anchor = "term-central-pupil-frame",
  },
  ["chamfer-distance"] = {
    label = "Chamfer Distance",
    short = "CD",
    anchor = "term-chamfer-distance",
  },
  ["coverage-ratio"] = {
    label = "Coverage Ratio",
    short = "CR",
    anchor = "term-coverage-ratio",
  },
  ["degrees-of-freedom"] = {
    label = "Degrees of Freedom",
    short = "DoF",
    anchor = "term-degrees-of-freedom",
  },
  ["egocentric-foundation-model-3d"] = {
    label = "Egocentric Foundation Model 3D",
    short = "EFM3D",
    anchor = "term-egocentric-foundation-model-3d",
  },
  ["egocentric-voxel-lifting"] = {
    label = "Egocentric Voxel Lifting",
    short = "EVL",
    anchor = "term-egocentric-voxel-lifting",
  },
  ["five-degrees-of-freedom"] = {
    label = "Five Degrees of Freedom",
    short = "5DoF",
    anchor = "term-five-degrees-of-freedom",
  },
  ["frustum"] = {
    label = "Frustum",
    short = "frustum",
    anchor = "term-frustum",
  },
  ["ground-truth"] = {
    label = "Ground Truth",
    short = "GT",
    anchor = "term-ground-truth",
  },
  ["left-up-forward"] = {
    label = "Left-Up-Forward",
    short = "LUF",
    anchor = "term-left-up-forward",
  },
  ["machine-perception-services"] = {
    label = "Machine Perception Services",
    short = "MPS",
    anchor = "term-machine-perception-services",
  },
  ["motion-trajectory-data"] = {
    label = "Motion Trajectory Data",
    short = "MTD",
    anchor = "term-motion-trajectory-data",
  },
  ["multi-frame-camera-data"] = {
    label = "Multi-Frame Camera Data",
    short = "MFCD",
    anchor = "term-multi-frame-camera-data",
  },
  ["multi-semi-dense-point-data"] = {
    label = "Multi-Semi-Dense Point Data",
    short = "MSDPD",
    anchor = "term-multi-semi-dense-point-data",
  },
  ["multi-view-stereo"] = {
    label = "Multi-view Stereo",
    short = "MVS",
    anchor = "term-multi-view-stereo",
  },
  ["next-best-view"] = {
    label = "Next-Best-View",
    short = "NBV",
    anchor = "term-next-best-view",
  },
  ["occupancy-grid"] = {
    label = "Occupancy Grid",
    short = "Occupancy Grid",
    anchor = "term-occupancy-grid",
  },
  ["oracle-rri"] = {
    label = "Oracle RRI",
    short = "oracle RRI",
    anchor = "term-oracle-rri",
  },
  ["oriented-bounding-box"] = {
    label = "Oriented Bounding Box",
    short = "OBB",
    anchor = "term-oriented-bounding-box",
  },
  ["point-cloud"] = {
    label = "Point Cloud",
    short = "PC",
    anchor = "term-point-cloud",
  },
  ["relative-reconstruction-improvement"] = {
    label = "Relative Reconstruction Improvement",
    short = "RRI",
    anchor = "term-relative-reconstruction-improvement",
  },
  ["scene-script-language"] = {
    label = "SceneScript Language",
    short = "SSL",
    anchor = "term-scene-script-language",
  },
  ["simultaneous-localization-and-mapping"] = {
    label = "Simultaneous Localization and Mapping",
    short = "SLAM",
    anchor = "term-simultaneous-localization-and-mapping",
  },
  ["six-degrees-of-freedom"] = {
    label = "Six Degrees of Freedom",
    short = "6DoF",
    anchor = "term-six-degrees-of-freedom",
  },
  ["snippet"] = {
    label = "Snippet",
    short = "snippet",
    anchor = "term-snippet",
  },
  ["target-conditioned-scorer"] = {
    label = "Target-Conditioned Scorer",
    short = "target-conditioned scorer",
    anchor = "term-target-conditioned-scorer",
  },
  ["target-of-interest"] = {
    label = "Target of Interest",
    short = "target",
    anchor = "term-target-of-interest",
  },
  ["target-specific-rri"] = {
    label = "Target-Specific RRI",
    short = "target RRI",
    anchor = "term-target-specific-rri",
  },
  ["track"] = {
    label = "Track",
    short = "track",
    anchor = "term-track",
  },
  ["view-introspection-network"] = {
    label = "View Introspection Network",
    short = "VIN",
    anchor = "term-view-introspection-network",
  },
  ["virtual-reality-standard"] = {
    label = "Virtual Reality Standard",
    short = "VRS",
    anchor = "term-virtual-reality-standard",
  },
  ["visual-inertial-odometry"] = {
    label = "Visual-Inertial Odometry",
    short = "VIO",
    anchor = "term-visual-inertial-odometry",
  },
}
