@startuml classes_projectaria_tools
set namespaceSeparator none
class "AriaDataViewer" as projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.AriaDataViewer {
  PLOT_COLORS_AND_SIZES_2D
  PLOT_COLORS_AND_SIZES_3D
  PLOT_SIZES_DEVICE_EXTRINSICS_BOXES
  config
  device_calibration : NoneType
  sensor_labels : NoneType
  slam_to_rgb_plot_scale : int
  vio_high_freq_traj_cached_full : list
  vio_traj_cached_full : list
  plot_audio(audio_data_and_record, num_audio_channels)
  plot_barometer(barometer_data)
  plot_device_extrinsics()
  plot_eye_gaze_data(eyegaze_data)
  plot_gps(gps_data)
  plot_hand_pose_data(hand_pose_data)
  plot_hand_pose_data_2d(hand_pose_data, camera_label: str)
  plot_hand_pose_data_3d(hand_pose_data)
  plot_image(frame, label, device_timestamp_ns)
  plot_imu(imu_data, label)
  plot_imu_batch_vectorized(imu_data_list, label)
  plot_magnetometer(magnetometer_data)
  plot_utc_timestamp(utc_timestamp_ns, camera_label: str, device_timestamp_ns)
  plot_vio_data(vio_data)
  plot_vio_high_freq_data(vio_high_freq_data)
  set_device_calibration(device_calibration)
  set_slam_to_rgb_plotting_ratio()
  update_rerun_blueprint()
}
class "AriaDataViewerConfig" as projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.AriaDataViewerConfig {
  audio_subsample_rate : int
  jpeg_quality : int
  vio_high_freq_subsample_rate : int
}
class "DatasetDownloadStatusManager" as projectaria_tools.tools.dataset_downloader.dataset_download_status_manager.DatasetDownloadStatusManager {
  status
  from_json(json_path: str) -> None
  get_download_status(data_type: str) -> bool
  set_download_status(data_type: str, value: bool)
  to_json(json_path: str)
}
class "DatasetDownloader" as projectaria_tools.tools.dataset_downloader.dataset_downloader.DatasetDownloader {
  data_types_all : dict
  data_types_selected : List[str]
  overwrite : bool
  sequence_config
  sequences : Optional[List[str]], list
  sequences_data
  download_data(output_folder: str)
}
class "DigitalTwinCatalogObjectsDownloader" as projectaria_tools.projects.dtc_objects.downloader_lib.DigitalTwinCatalogObjectsDownloader {
  cdn_data
  file_key_prefixes : Optional[List[str]], list
  file_keys : Optional[List[str]], list
  objects : Optional[List[str]], list
  output_folder : str
  releases
  download_data()
  get_object_cdn_entry(release: str, dtc_object: str) -> dict
}
class "SensorLabels" as projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.SensorLabels {
  barometer_labels : List[str]
  contact_microphone_label : str
  eye_gaze_label : Optional[str]
  eye_tracking_camera_labels : List[str]
  gps_label : str
  hand_tracking_label : Optional[str]
  imu_labels : List[str]
  magnetometer_label : str
  microphone_label : str
  rgb_and_slam_labels : List[str]
  rgb_label : str
  slam_labels : List[str]
  vio_high_freq_label : Optional[str]
  vio_label : Optional[str]
  from_device_version(device_version: DeviceVersion)
}
class "Vrs2Mp4Converter" as projectaria_tools.tools.vrs_to_mp4.vrs_to_mp4_utils.Vrs2Mp4Converter {
  OUTPUT_AUDIO_CHANNELS : list
  audio_channels_ : Optional[List[int]]
  audio_config
  audio_num_channels
  audio_streamid_
  contain_audio_
  contain_rgb_
  device_version_ : NoneType
  down_sampling_factor_ : int
  duplicated_frames_ : ndarray
  end_timestamp_ns_
  image_prev_index_
  image_streamid_
  invalid_frames_ : ndarray
  last_time_ns_
  last_valid_image_ : ndarray
  mp4_to_vrs_timestamp_ns_ : dict
  provider_
  skipped_frames_ : ndarray
  start_timestamp_ns_
  audio_buffersize()
  contain_audio() -> bool
  convert_image(image_data_and_record)
  duration_ns()
  make_audio_data(t) -> np.ndarray
  make_frame(t) -> np.ndarray
  video_fps()
  write_log(log_path: str)
  write_mp4_to_vrs_time_ns(log_path: str) -> np.ndarray
}
projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.AriaDataViewer --> projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.AriaDataViewerConfig : config
projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.SensorLabels --* projectaria_tools.tools.aria_rerun_viewer.aria_data_plotter.AriaDataViewer : sensor_labels
@enduml
