@startuml classes_ATEK
set namespaceSeparator none
class "AriaCameraProcessor" as atek.data_preprocess.processors.aria_camera_processor.AriaCameraProcessor {
  camera_calibration : NoneType
  camera_label
  camera_timestamps
  conf : DictConfig
  data_provider
  final_camera_calib
  original_camera_calib
  rescale_antialias : bool
  rotate_image_cw90deg : bool
  scale
  stream_id
  target_camera_resolution : List
  time_domain
  undistort_to_linear_camera : bool
  undistorted_linear_camera_calib
  video_vrs : str
  get_final_camera_calib()
  get_image_data_by_timestamps_ns(timestamps_ns: List[int]) -> Optional[MultiFrameCameraData]
  get_image_transform(rescale_interpolation: InterpolationMode, is_transforming_label_data: bool) -> Callable
  get_origin_label()
  get_pixel_transform() -> Callable
  get_stream_id()
  setup_camera_calibration()
  setup_vrs_data_provider()
}
class "AriaCameraProcessorTest" as atek.data_preprocess.test.aria_camera_processor_test.AriaCameraProcessorTest {
  setUp() -> None
  test_get_image_data() -> None
}
class "AtekDataPathsProvider" as atek.data_preprocess.sample_builders.atek_data_paths_provider.AtekDataPathsProvider {
  atek_data_paths : dict
  data_root_path : str
  get_data_paths() -> Dict[str, str]
}
class "AtekDataSample" as atek.data_preprocess.atek_data_sample.AtekDataSample {
  camera_rgb : Optional[MultiFrameCameraData]
  camera_rgb_depth : Optional[MultiFrameCameraData]
  camera_slam_left : Optional[MultiFrameCameraData]
  camera_slam_right : Optional[MultiFrameCameraData]
  gt_data : Dict
  mps_online_calib_data : Optional[MpsOnlineCalibData]
  mps_semidense_point_data : Optional[MpsSemiDensePointData]
  mps_traj_data : Optional[MpsTrajData]
  sequence_name : Optional[str]
  to_flatten_dict()
}
class "AtekDataSampleTest" as atek.data_preprocess.test.atek_data_sample_test.AtekDataSampleTest {
  setUp() -> None
  test_flatten_to_dict() -> None
}
class "AtekObb3CsvReader" as atek.evaluation.static_object_detection.obb3_csv_io.AtekObb3CsvReader {
  input_filename : str
  read_as_obb_dict() -> Dict
}
class "AtekObb3CsvWriter" as atek.evaluation.static_object_detection.obb3_csv_io.AtekObb3CsvWriter {
  file_writer
  output_filename : str
  flush() -> None
  write_from_atek_dict(atek_dict: Dict, confidence_score: Optional[torch.Tensor], timestamp_ns: int, flush_at_end: bool) -> None
  write_from_cubercnn_dict(cubercnn_dict: Dict, timestamp_ns: int, flush_at_end: bool) -> None
}
class "AtekObb3Metrics" as atek.evaluation.static_object_detection.static_object_detection_metrics.AtekObb3Metrics {
  metric_3d
  sem_id_to_name : NoneType
  compute()
  forward(prediction: Dict, target: Dict)
  reset()
  update(prediction: Dict, target: Dict)
}
class "AtekRawDataloaderAsCubercnn" as atek.data_loaders.atek_raw_dataloader_as_cubercnn.AtekRawDataloaderAsCubercnn {
  model_adaptor
  sample_builder
  subsampler
  get_atek_sample_at_timestamp_ns(timestamp_ns: int) -> Optional[AtekDataSample]
  get_model_specific_sample_at_timestamp_ns(timestamp_ns: int) -> Optional[Dict]
  get_timestamps_by_sample_index(index: int)
}
class "AtekWdsWriter" as atek.data_preprocess.atek_wds_writer.AtekWdsWriter {
  current_sample_idx : int
  max_samples_per_shard
  output_path : str
  prefix_string
  remove_last_tar_if_not_full : bool
  samples_in_current_shard : int
  sink : NoneType, ShardWriter
  add_sample(data_sample: AtekDataSample)
  close()
  get_num_samples()
}
class "CameraTemporalSubsampler" as atek.data_preprocess.subsampling_lib.temporal_subsampler.CameraTemporalSubsampler {
  conf : DictConfig
  sample_length
  stride
  subsampled_timestamps
  total_num_samples : int
  get_timestamps_by_sample_index(sample_index: int) -> List[int]
  get_total_num_samples() -> int
}
class "CubeRCNNModelAdaptor" as atek.data_loaders.cubercnn_model_adaptor.CubeRCNNModelAdaptor {
  max_bb3d_depth : Optional[float]
  min_bb2d_area : Optional[float]
  min_bb3d_depth : Optional[float]
  atek_to_cubercnn(data)
  cubercnn_gt_to_atek_gt(cubercnn_dict: Dict, T_world_camera_np: np.array, camera_label: str, cubercnn_id_to_atek_id: Optional[Dict[int, int]]) -> Optional[Dict]
  get_dict_key_mapping_all()
}
class "CubercnnVisualizer" as atek.viz.cubercnn_visualizer.CubercnnVisualizer {
  cameras_to_plot : list
  plot_cubercnn_dict(cubercnn_dict: Dict, timestamp_ns: int, plot_color: List[int], suffix: str) -> None
  plot_cubercnn_img(cubercnn_img: torch.Tensor, timestamp_ns: int) -> None
}
class "DepthImageProcessor" as atek.data_preprocess.processors.depth_image_processor.DepthImageProcessor {
  cached_unprojected_ray_norm
  camera_timestamps
  conf : DictConfig
  convert_zdepth_to_distance_flag
  data_provider
  depth_camera_calib
  depth_camera_label : str
  depth_vrs : str
  image_transform : Callable
  stream_id : NoneType
  time_domain
  get_depth_data_by_timestamps_ns(timestamps_ns: List[int]) -> Optional[MultiFrameCameraData]
  setup_vrs_data_provider()
}
class "DepthImageProcessorTest" as atek.data_preprocess.test.depth_image_processor_test.DepthImageProcessorTest {
  setUp() -> None
  test_get_depth_image_data() -> None
}
class "DistortByCalibrationTVWrapper" as atek.data_preprocess.processors.aria_camera_processor.AriaCameraProcessor.DistortByCalibrationTVWrapper {
  dstCalib
  is_transforming_label_data : bool
  srcCalib
}
class "EfmGtProcessor" as atek.data_preprocess.processors.efm_gt_processor.EfmGtProcessor {
  get_gt_by_timestamp_list_ns(timestamps_ns: List[int]) -> Optional[Dict]
}
class "EfmSampleBuilder" as atek.data_preprocess.sample_builders.efm_sample_builder.EfmSampleBuilder {
  conf : DictConfig
  depth_vrs_file : str
  processors : dict
  sequence_name : str
  vrs_file : str
  get_sample_by_timestamps_ns(timestamps_ns: List[int]) -> Optional[AtekDataSample]
}
class "FileIoUtilsTest" as atek.data_preprocess.test.file_io_utils_test.FileIoUtilsTest {
  setUp() -> None
  test_separate_tensor_from_dict_round_trip() -> None
  test_separate_tensors_from_dict() -> None
}
class "GeneralAtekPreprocessor" as atek.data_preprocess.general_atek_preprocessor.GeneralAtekPreprocessor {
  atek_visualizer : Optional[NativeAtekSampleVisualizer]
  atek_wds_writer : Optional[AtekWdsWriter]
  sample_builder
  subsampler
  process_all_samples(write_to_wds_flag: bool, viz_flag: bool) -> int
}
class "GroupAtekObb3CsvWriter" as atek.evaluation.static_object_detection.obb3_csv_io.GroupAtekObb3CsvWriter {
  output_filename
  output_folder : str
  per_sequence_writers : dict
  flush() -> None
  write_from_atek_dict(atek_dict: Dict, sequence_name: str, confidence_score: Optional[torch.Tensor], timestamp_ns: int, flush_at_end: bool) -> None
}
class "ImuData" as atek.data_preprocess.atek_data_sample.ImuData {
  T_Device_Imu : Tensor
  accel_rect_bias : Tensor
  accel_rect_matrix : Tensor
  capture_timestamps_ns : Tensor
  gyro_rect_bias : Tensor
  gyro_rect_matrix : Tensor
  imu_label : str
  raw_accel_data : Tensor
  raw_gyro_data : Tensor
  rectified_accel_data : Tensor
  rectified_gyro_data : Tensor
  to_flatten_dict()
}
class "IouOutputs" as atek.evaluation.static_object_detection.eval_obb3_metrics_utils.IouOutputs {
  iou : Tensor
  vol : Tensor
}
class "LoadAtekWdsDatasetTest" as atek.data_loaders.test.atek_wds_dataloader_test.LoadAtekWdsDatasetTest {
  expected_flattened_samples : list
  output_wds_path
  temp_dir_object : TemporaryDirectory
  setUp() -> None
  tearDown()
  test_atek_default_collation() -> None
  test_atek_native_round_trip() -> None
}
class "MAPMetricResults3D" as atek.evaluation.static_object_detection.static_object_detection_metrics.MAPMetricResults3D {
  map
  map_25
  map_50
}
class "MeanAveragePrecision3D" as atek.evaluation.static_object_detection.static_object_detection_metrics.MeanAveragePrecision3D {
  bbox_area_ranges : dict
  class_metrics : bool
  eval_imgs : NoneType
  max_detection_thresholds
  ret_all_prec_rec : bool
  compute(sem_id_to_name_mapping: Optional[Dict[int, str]]) -> dict
  update(preds: List[Dict[str, torch.Tensor]], target: List[Dict[str, torch.Tensor]]) -> None
}
class "MpsOnlineCalibData" as atek.data_preprocess.atek_data_sample.MpsOnlineCalibData {
  capture_timestamps_ns : Optional[torch.Tensor]
  projection_params : Optional[torch.Tensor]
  ts_device_camera : Optional[torch.Tensor]
  utc_timestamps_ns : Optional[torch.Tensor]
  to_flatten_dict()
}
class "MpsOnlineCalibProcessor" as atek.data_preprocess.processors.mps_online_calib_processor.MpsOnlineCalibProcessor {
  conf : DictConfig
  mps_data_provider
  get_online_calibration_by_timestamps_ns(timestamps_ns: List[int]) -> Optional[MpsOnlineCalibData]
}
class "MpsOnlineCalibProcessorTest" as atek.data_preprocess.test.mps_processor_test.MpsOnlineCalibProcessorTest {
  setUp() -> None
  test_get_online_calib_data() -> None
}
class "MpsSemiDensePointData" as atek.data_preprocess.atek_data_sample.MpsSemiDensePointData {
  capture_timestamps_ns : Tensor
  points_dist_std : List[torch.Tensor]
  points_inv_dist_std : List[torch.Tensor]
  points_volume_max : Tensor
  points_volume_min : Tensor
  points_world : List[torch.Tensor]
  to_flatten_dict()
}
class "MpsSemiDenseProcessor" as atek.data_preprocess.processors.mps_semidense_processor.MpsSemiDenseProcessor {
  conf : DictConfig
  time_to_uids : defaultdict
  uid_to_dist_std : dict
  uid_to_inv_dist_std : dict
  uid_to_p3 : dict
  uid_to_times : defaultdict
  vol_max
  vol_min
  get_semidense_points_by_timestamps_ns(timestamps_ns: List[int]) -> Optional[MpsSemiDensePointData]
}
class "MpsSemiDenseProcessorTest" as atek.data_preprocess.test.mps_processor_test.MpsSemiDenseProcessorTest {
  setUp() -> None
  test_get_semidense_data() -> None
}
class "MpsTrajData" as atek.data_preprocess.atek_data_sample.MpsTrajData {
  Ts_World_Device : Tensor
  capture_timestamps_ns : Tensor
  gravity_in_world : Tensor
  tensor_field_names()
  to_flatten_dict()
}
class "MpsTrajProcessor" as atek.data_preprocess.processors.mps_traj_processor.MpsTrajProcessor {
  conf : DictConfig
  mps_data_provider
  get_closed_loop_pose_by_timestamps_ns(timestamps_ns: List[int], interpolate: bool) -> Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor]]
}
class "MpsTrajProcessorTest" as atek.data_preprocess.test.mps_processor_test.MpsTrajProcessorTest {
  setUp() -> None
  test_get_traj_data() -> None
}
class "MultiFrameCameraData" as atek.data_preprocess.atek_data_sample.MultiFrameCameraData {
  T_Device_Camera : Tensor
  camera_label : str
  camera_model_name : str
  camera_valid_radius : Tensor
  capture_timestamps_ns : Tensor
  exposure_durations_s : Tensor
  frame_ids : Tensor
  gains : Tensor
  images : Tensor
  origin_camera_label : str
  projection_params : Tensor
  image_field_names()
  str_field_names()
  tensor_field_names()
  to_flatten_dict()
}
class "MultiFrameCameraDataTest" as atek.data_preprocess.test.atek_data_sample_test.MultiFrameCameraDataTest {
  setUp() -> None
  test_flatten_to_dict() -> None
}
class "NativeAtekSampleVisualizer" as atek.viz.atek_visualizer.NativeAtekSampleVisualizer {
  AXIS_LENGTH : float
  COLOR_BLUE : list
  COLOR_GRAY : list
  COLOR_GREEN : list
  COLOR_RED : list
  MAX_LIMIT_TO_VIZ_IN_SEMIDENSE_POINTS : int
  MAX_OBB_PER_BATCH : int
  cameras_to_plot : list
  conf : Optional[DictConfig]
  mps_traj_cached_full : list
  obb_labels_to_ignore : NoneType
  obb_labels_to_include : NoneType
  output_viz_file : Optional[str]
  viz_prefix : str
  plot_atek_sample(atek_data_sample: Optional[AtekDataSample], plot_line_color, suffix) -> None
  plot_atek_sample_as_dict(atek_data_sample_dict: Dict, plot_line_color, suffix) -> None
  plot_atek_sample_gt(atek_data_sample: AtekDataSample, timestamp_ns: int, plot_color: List[int], suffix: str) -> None
  plot_atek_sample_no_gt(atek_data_sample: Optional[AtekDataSample]) -> None
  plot_efm_gt(gt_dict, plot_color, suffix) -> None
  plot_mps_traj_data(mps_traj_data: Optional[MpsTrajData]) -> None
  plot_multi_frame_camera_data(camera_data: Optional[MultiFrameCameraData]) -> None
  plot_obb2_gt(gt_dict, timestamp_ns, plot_color, suffix) -> None
  plot_obb3_gt(gt_dict, timestamp_ns, plot_color, suffix) -> None
  plot_obb3d_in_camera_view(obb3d_gt_dict: dict, camera_data: Optional[MultiFrameCameraData], mps_traj_data: Optional[MpsTrajData]) -> None
  plot_semidense_point_cloud(mps_semidense_point_data: Optional[MpsSemiDensePointData]) -> None
  save_viz() -> None
  show_on_notebook() -> None
}
class "Obb2GtProcessor" as atek.data_preprocess.processors.obb2_gt_processor.Obb2GtProcessor {
  adt_gt_provider
  camera_label_to_calibs : Optional[Dict[str, CameraCalibration]]
  camera_label_to_pixel_transforms : Optional[Dict[str, Callable]]
  camera_label_to_stream_ids : Dict[str, str]
  category_mapping : NoneType
  conf : DictConfig
  get_gt_by_timestamp_ns(timestamp_ns: int) -> Optional[Dict]
}
class "Obb2GtProcessorTest" as atek.data_preprocess.test.obb2_gt_processor_test.Obb2GtProcessorTest {
  setUp() -> None
  test_get_obb2_gt_data() -> None
}
class "Obb3GtProcessor" as atek.data_preprocess.processors.obb3_gt_processor.Obb3GtProcessor {
  adt_gt_provider
  camera_label_to_stream_ids : Dict[str, StreamId]
  category_mapping : NoneType
  conf : DictConfig
  get_gt_by_timestamp_ns(timestamp_ns: int) -> Optional[Dict]
}
class "Obb3GtProcessorTest" as atek.data_preprocess.test.obb3_gt_processor_test.Obb3GtProcessorTest {
  setUp() -> None
  test_get_obb3_gt_data() -> None
}
class "ObbSampleBuilder" as atek.data_preprocess.sample_builders.obb_sample_builder.ObbSampleBuilder {
  conf : DictConfig
  processors : dict
  sequence_name : str
  vrs_file : str
  get_sample_by_timestamp_ns(timestamp_ns: int) -> Optional[AtekDataSample]
  get_sample_by_timestamps_ns(timestamps_ns: List[int]) -> Optional[AtekDataSample]
}
class "ObbSampleBuilderTest" as atek.data_preprocess.test.obb_sample_builder_test.ObbSampleBuilderTest {
  setUp() -> None
  test_get_obb3_sample() -> None
}
class "Sam2ModelAdaptor" as atek.data_loaders.sam2_model_adaptor.Sam2ModelAdaptor {
  num_boxes : int
  atek_to_sam2(data)
  get_dict_key_mapping_all()
}
class "TestMpsSemiDensePointData" as atek.data_preprocess.test.atek_data_sample_test.TestMpsSemiDensePointData {
  test_to_flatten_dict()
}
atek.data_preprocess.processors.efm_gt_processor.EfmGtProcessor --|> atek.data_preprocess.processors.obb3_gt_processor.Obb3GtProcessor
atek.viz.cubercnn_visualizer.CubercnnVisualizer --|> atek.viz.atek_visualizer.NativeAtekSampleVisualizer
atek.data_loaders.cubercnn_model_adaptor.CubeRCNNModelAdaptor --* atek.data_loaders.atek_raw_dataloader_as_cubercnn.AtekRawDataloaderAsCubercnn : model_adaptor
atek.data_preprocess.atek_data_sample.MpsTrajData --* atek.data_preprocess.atek_data_sample.AtekDataSample : mps_traj_data
atek.data_preprocess.sample_builders.obb_sample_builder.ObbSampleBuilder --* atek.data_loaders.atek_raw_dataloader_as_cubercnn.AtekRawDataloaderAsCubercnn : sample_builder
atek.data_preprocess.subsampling_lib.temporal_subsampler.CameraTemporalSubsampler --* atek.data_loaders.atek_raw_dataloader_as_cubercnn.AtekRawDataloaderAsCubercnn : subsampler
atek.evaluation.static_object_detection.static_object_detection_metrics.MeanAveragePrecision3D --* atek.evaluation.static_object_detection.static_object_detection_metrics.AtekObb3Metrics : metric_3d
atek.data_preprocess.atek_wds_writer.AtekWdsWriter --o atek.data_preprocess.general_atek_preprocessor.GeneralAtekPreprocessor : atek_wds_writer
atek.viz.atek_visualizer.NativeAtekSampleVisualizer --o atek.data_preprocess.general_atek_preprocessor.GeneralAtekPreprocessor : atek_visualizer
@enduml
